# ~/.tmuxinator/dev.yml

name: dev
root: .
socket_name: dev
pre:
  - brew services start postgres 2> /dev/null

windows:
  - server: bundle exec rails s
  - editor:
      layout: 0e3e,185x52,0,0{112x52,0,0,0,72x52,113,0,1}
      panes:
        - vim
        - clear # useful for shell commands
  - console: bundle exec rails c
