# ~/.tmuxinator/dev.yml

name: dev
root: .
socket_name: dev
pre:
  - brew services start postgres 2> /dev/null

windows:
  - server: bundle exec rails s
  - editor:
      layout: main-horizontal
      panes:
        - vim
        - clear # useful for shell commands
  - console: bundle exec rails c
